/** @type { import('prettier').Config & import('@ianvs/prettier-plugin-sort-imports').PluginConfig & import('prettier-plugin-tailwindcss').PluginOptions } */
const config = {
  useTabs: false,
  semi: true,
  trailingComma: 'es5',
  singleQuote: true,
  printWidth: 120,
  tabWidth: 2,
  arrowParens: 'avoid',
  jsxSingleQuote: true,
  endOfLine: 'auto',
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(react-dom/(.*)$)|^(react-dom$)',
    '',
    '^(@tanstack/(.*)$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^~/types/(.*)$',
    '^~/config/(.*)$',
    '^~/db/(.*)$|^~/db$',
    '^~/lib/(.*)$',
    '^~/emails/(.*)$',
    '^~/server/(.*)$',
    '^~/layouts/(.*)$',
    '^~/components/(.*)$',
    '^~/routes/(.*)$',
    '^~/assets/(.*)$',
    '^~/styles/(.*)$',
    '',
    '^[./]',
  ],
  tailwindAttributes: ['containerClassName', 'imageClassName'],
  tailwindFunctions: ['cva'],
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
};

export default config;
